/**
 * Mock data for development/offline fallback
 * Used when WordPress API is unavailable
 */

export const mockCategories = [
  { id: 1, _id: "1", title: "Breakfast", slug: "breakfast", description: "Easy breakfast recipes" },
  { id: 2, _id: "2", title: "Lunch", slug: "lunch", description: "Healthy lunch ideas" },
  { id: 3, _id: "3", title: "Dinner", slug: "dinner", description: "Delicious dinner recipes" },
  { id: 4, _id: "4", title: "Desserts", slug: "desserts", description: "Sweet treats and desserts" },
  { id: 5, _id: "5", title: "Snacks", slug: "snacks", description: "Quick snack recipes" },
];

export const mockPosts = [
  {
    _id: "1",
    id: 1,
    title: "Fluffy Chocolate Chip Pancakes",
    slug: "fluffy-chocolate-chip-pancakes",
    excerpt: "Light and fluffy pancakes loaded with chocolate chips. Perfect for a weekend breakfast!",
    content: "Perfect breakfast for any occasion.",
    category: mockCategories[0],
    featuredImage: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=500&h=300&fit=crop",
    featuredImageAlt: "Chocolate chip pancakes",
    author: { name: "Recipe Team", avatar: "https://secure.gravatar.com/avatar/default" },
    publishedAt: new Date().toISOString(),
    featured: true,
    readTime: 5,
  },
  {
    _id: "2",
    id: 2,
    title: "Mediterranean Grain Bowl",
    slug: "mediterranean-grain-bowl",
    excerpt: "A colorful and nutritious lunch bowl with quinoa, vegetables, and tahini dressing.",
    content: "Healthy lunch option.",
    category: mockCategories[1],
    featuredImage: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=500&h=300&fit=crop",
    featuredImageAlt: "Mediterranean grain bowl",
    author: { name: "Recipe Team", avatar: "https://secure.gravatar.com/avatar/default" },
    publishedAt: new Date(Date.now() - 86400000).toISOString(),
    featured: false,
    readTime: 8,
  },
  {
    _id: "3",
    id: 3,
    title: "Garlic Butter Pasta with Shrimp",
    slug: "garlic-butter-pasta-shrimp",
    excerpt: "Restaurant-quality shrimp pasta that you can make at home in 20 minutes.",
    content: "Easy weeknight dinner.",
    category: mockCategories[2],
    featuredImage: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500&h=300&fit=crop",
    featuredImageAlt: "Garlic butter pasta with shrimp",
    author: { name: "Recipe Team", avatar: "https://secure.gravatar.com/avatar/default" },
    publishedAt: new Date(Date.now() - 172800000).toISOString(),
    featured: false,
    readTime: 15,
  },
  {
    _id: "4",
    id: 4,
    title: "No-Bake Chocolate Cheesecake Bites",
    slug: "no-bake-chocolate-cheesecake-bites",
    excerpt: "Decadent chocolate cheesecake bites that require no baking. Perfect for parties!",
    content: "Delicious dessert.",
    category: mockCategories[3],
    featuredImage: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&h=300&fit=crop",
    featuredImageAlt: "Chocolate cheesecake bites",
    author: { name: "Recipe Team", avatar: "https://secure.gravatar.com/avatar/default" },
    publishedAt: new Date(Date.now() - 259200000).toISOString(),
    featured: true,
    readTime: 10,
  },
  {
    _id: "5",
    id: 5,
    title: "Crispy Chickpea Buddha Bowl",
    slug: "crispy-chickpea-buddha-bowl",
    excerpt: "A hearty and satisfying lunch with roasted chickpeas and fresh vegetables.",
    content: "Vegetarian lunch.",
    category: mockCategories[1],
    featuredImage: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop",
    featuredImageAlt: "Crispy chickpea buddha bowl",
    author: { name: "Recipe Team", avatar: "https://secure.gravatar.com/avatar/default" },
    publishedAt: new Date(Date.now() - 345600000).toISOString(),
    featured: false,
    readTime: 12,
  },
  {
    _id: "6",
    id: 6,
    title: "Honey Glazed Salmon",
    slug: "honey-glazed-salmon",
    excerpt: "Perfectly cooked salmon with a sweet and savory honey glaze.",
    content: "Elegant dinner.",
    category: mockCategories[2],
    featuredImage: "https://images.unsplash.com/photo-1505521585350-ea646e4060ca?w=500&h=300&fit=crop",
    featuredImageAlt: "Honey glazed salmon",
    author: { name: "Recipe Team", avatar: "https://secure.gravatar.com/avatar/default" },
    publishedAt: new Date(Date.now() - 432000000).toISOString(),
    featured: true,
    readTime: 20,
  },
  {
    _id: "7",
    id: 7,
    title: "Homemade Granola Bars",
    slug: "homemade-granola-bars",
    excerpt: "Chewy and crunchy granola bars perfect for snacking or meal prep.",
    content: "Healthy snack.",
    category: mockCategories[4],
    featuredImage: "https://images.unsplash.com/photo-1464454709131-ffd692591ee5?w=500&h=300&fit=crop",
    featuredImageAlt: "Homemade granola bars",
    author: { name: "Recipe Team", avatar: "https://secure.gravatar.com/avatar/default" },
    publishedAt: new Date(Date.now() - 518400000).toISOString(),
    featured: false,
    readTime: 8,
  },
];
